*******************************************************************************
*** State Legislative Primary Election Data
*** Andy Myers
*** Compute in-text statistics and export as LaTeX macros
*******************************************************************************

gl path "~/Dropbox/StateLegElectionData"

local outfile "$path/draft/output/intext_stats.tex"
cap file close texfile
file open texfile using "`outfile'", write replace

*******************************************************************************
*** Stats from public dataset (only obs with vote totals)
*******************************************************************************

use "$path/analysis_data/public/stateleg_prim_elec_data.dta", clear

// Total observations
local N_obs : di %12.0fc _N
local N_obs = strtrim("`N_obs'")

// Number of variables
describe, short
local N_vars = r(k)

// Distinct primary races
preserve
	bysort primary_race_id: keep if _n == 1
	local N_races : di %12.0fc _N
	local N_races = strtrim("`N_races'")
restore

// Approximate distinct candidates (unique first + last + state)
preserve
	bysort last_name first_name state: keep if _n == 1
	local N_cands : di %12.0fc _N
	local N_cands = strtrim("`N_cands'")
restore

*******************************************************************************
*** Write LaTeX newcommands
*******************************************************************************

// Full dataset
file write texfile "% In-text statistics — auto-generated by make_intext_stats.do" _n
file write texfile "% Do not edit by hand" _n
file write texfile "\newcommand{\NobsAll}{`N_all'}" _n
file write texfile "\newcommand{\NracesAll}{`N_races_all'}" _n

// Public dataset
file write texfile "\newcommand{\Nobs}{`N_obs'}" _n
file write texfile "\newcommand{\Nraces}{`N_races'}" _n
file write texfile "\newcommand{\Ncands}{`N_cands'}" _n
file write texfile "\newcommand{\Nvars}{`N_vars'}" _n

file close texfile

di "Macros written to `outfile'"
